version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10.1
    working_directory: ~/eats-frontend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
          # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: install dependencies 
          command: cd client/ && yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}
      - run: 
          name: run tests
          command: cd client && yarn test
  deploy:
    docker:
      - image: circleci/node:9.10.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run: 
          name: install dependencies 
          command: cd client/ && yarn install
      - run: 
          name: create application artifacts
          command: cd client && npm run build:production
      - run:
          name: Deploy application to environment
          command: |
            chmod +x scripts/deploy.sh && ./scripts/deploy.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /(release|hotfix)\/v[0-9].[0-9].[0-9]/